### PR TITLE
replace outdated logo with current

### PR DESCRIPTION
**Pull request by olafk**
The Liferay Waffle logo used within IDE has been retired years ago. See https://liferay.design/
Replacement based on images found when looking for filenames containing "logo" - I might have missed others

### CODE REVIEW

**Comment by gamerson** [comment]
hey @simonjhy  could you review this and then send to me over at https://github.com/gamerson/liferay-ide when done?  Thanks!.

**Comment by gamerson** [comment]
hey @olafk  appreciate you getting this conversation started.  Ashley is going to create a document that we could collaborate further on to get everything we need.

**Comment by yanan** [comment]
Hello @olafk , there're three icons which I haven't found suitable ones: https://docs.google.com/document/d/1URDxWq4IceQrQ6VkWDfzGQa6AgUFetzVaOESKUNJ3iE/edit

Could you help check and see if there is any suitable icons when you're available? Thanks

**Comment by olafk** [comment]
Thanks, 
For my pr, I've just scaled down the logo that I found on liferay.design. For the other icons that are listed in the google doc, I could edit them as well (e.g. add a "+" on top), but it might also be something that our design folks could do - especially as they might have an opinion on how tiny logos should look like (for example the 8*8 px nature overlay). 
Let me know if you'd like me to try out my gimp superpowers or rather create a LRDESIGN ticket to get the resident pixel artists involved.

**Comment by yanan** [comment]
Thanks @olafk , we've merged this into master, I'm going to close this pr.

**Pull request closed without merging**
